{{- if .Values.global.certificate }}
apiVersion: v1
data:
  ca.pem: |
    {{ .Values.global.certificate | nindent 4 }}
kind: ConfigMap
metadata:
  name: ca-pemstore
  namespace: {{ tpl .Values.global.namespace . }}
{{- end }}
