apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Values.global.name }}-agent
rules:
- apiGroups:
  - ""
  resources:
  - endpoints
  - services
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - namespaces
  - pods
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - pods/exec
  verbs:
  - get
  - create
- apiGroups:
  - ""
  resources:
  - nodes
  - nodes/metrics
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - apps
  resources:
  - daemonsets
  {{- if eq .Values.agent.resource.kind "StatefulSet" }}
  - statefulsets
  {{- end }}
  verbs:
  - get
{{- if eq .Values.global.internal "enable" }}
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
  - list
  - watch
{{- end }}
{{- if .Values.clusterRoleRules }}
{{ toYaml .Values.clusterRoleRules }}
{{- end }}
