apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Values.global.name }}-agent
rules:
- apiGroups:
  - ""
  resources:
  - endpoints
  - services
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - namespaces
  - pods
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - pods/exec
  verbs:
  - get
  - create
- apiGroups:
  - ""
  resources:
  - nodes
  - nodes/metrics
  verbs:
  - get
  - list
  - patch
  - watch
{{- if .Values.clusterRoleRules }}
{{ toYaml .Values.clusterRoleRules }}
{{- end }}
