apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Values.global.name }}-sa-view-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Values.global.name }}-agent
subjects:
- kind: ServiceAccount
  name: {{ .Values.global.name }}-sa
  namespace: {{ .Release.Namespace }}
