apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ tpl .Values.global.namespace . }}-sa-view-role-binding
  namespace: {{ tpl .Values.global.namespace . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ .Values.global.name }}-agent-role
subjects:
- kind: ServiceAccount
  name: {{ tpl .Values.global.namespace . }}-sa
  namespace: {{ tpl .Values.global.namespace . }}
