apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Values.global.name }}-sa-view-role-binding
  namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ .Values.global.name }}-agent-role
subjects:
- kind: ServiceAccount
  name: {{ .Values.global.name }}-sa
  namespace: {{ .Release.Namespace }}
