apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ .Values.global.name }}-agent-role
  namespace: {{ tpl .Values.global.namespace . }}
rules:
- apiGroups:
  - ""
  resources:
  - pods/log
  verbs:
  - get
  - list
{{- if .Values.shorelineRoleRules }}
{{- toYaml .Values.shorelineRoleRules }}
{{- end }}
