apiVersion: v1
kind: Secret
metadata:
  name: customer-secret
  namespace: {{ tpl .Values.global.namespace . }}
  labels:
    app : {{ .Values.global.name }}
type: Opaque
data:
  customer-secret: {{ required "customer secret is a required field" .Values.global.customer_secret | b64enc | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.global.name }}-agent
  namespace: {{ tpl .Values.global.namespace . }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "imagePullSecret" . }}