{{- if .Values.global.customer_secret }}
apiVersion: v1
kind: Secret
metadata:
  name: customer-secret
  namespace: {{ .Release.Namespace }}
  labels:
    app : {{ .Values.global.name }}
type: Opaque
data:
  customer-secret: {{ .Values.global.customer_secret | b64enc | quote }}
{{- end }}
---
{{- if .Values.agent.resource.imageCredentials }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.global.name }}-agent
  namespace: {{ .Release.Namespace }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "imagePullSecret" . }}
{{- end }}