apiVersion: v1
kind: ServiceAccount
metadata:
  {{- if and (eq .Values.agent.serviceaccount.irsa true) (ne .Values.agent.serviceaccount.aws_role "") }}
  annotations:
    eks.amazonaws.com/role-arn: {{ .Values.agent.serviceaccount.aws_role }}
  {{- end }}
  name: {{ tpl .Values.global.namespace . }}-sa
  namespace: {{ tpl .Values.global.namespace . }}
