apiVersion: v1
kind: ServiceAccount
metadata:
  {{- if or (and (eq .Values.agent.serviceaccount.irsa true) (ne .Values.agent.serviceaccount.aws_role "")) (.Values.agent.serviceaccount.annotations) }}
  annotations:
    {{- if and (eq .Values.agent.serviceaccount.irsa true) (ne .Values.agent.serviceaccount.aws_role "") }}
    eks.amazonaws.com/role-arn: {{ .Values.agent.serviceaccount.aws_role }}
    {{- end }}
    {{- if .Values.agent.serviceaccount.annotations }}
    {{- toYaml .Values.agent.serviceaccount.annotations | nindent 4 }}
    {{- end }}
  {{- end }}
  name: {{ tpl .Values.global.namespace . }}-sa
  namespace: {{ tpl .Values.global.namespace . }}
