{{- if eq .Values.agent.resource.hpa "enable" }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ .Values.global.name }}
  namespace: {{ .Release.Namespace }}
spec:
  minReplicas: {{ .Values.agent.resource.hpaValues.minReplicas }}
  maxReplicas: {{ .Values.agent.resource.hpaValues.maxReplicas }}
  metrics:
    {{- if .Values.agent.resource.hpaValues.metrics }}
    {{- toYaml .Values.agent.resource.hpaValues.metrics | nindent 2 }}
    {{- end }}
  behavior:
    {{- if .Values.agent.resource.hpaValues.behavior }}
    {{- toYaml .Values.agent.resource.hpaValues.behavior | nindent 4 }}
    {{- end }}
  scaleTargetRef:
    apiVersion: apps/v1
    kind: StatefulSet
    name: {{ .Values.global.name }}
{{- end }}