global:
  name: "shoreline"
  namespace: "{{ ternary \"shoreline\" .Release.Namespace (eq .Release.Namespace \"default\") }}"
  customer_id: ""
  customer_secret: ""
  customer_endpoint: ""
  cloud_provider: "aws"
agent:
  serviceaccount:
    irsa: false
    aws_role: ""
  resource:
    kind: "DaemonSet"
    replicas: 1
    image: "shorelinesoftware/agent"
    tag: "release-5.0.23"
    resources:
      limits:
        cpu: "500m"
        memory: "500Mi"
      requests:
        cpu: "500m"
        memory: "500Mi"
    volumeMounts:
      mountPaths:
        varlog: "/var/log"
        varlibdockercontainers: "/var/lib/docker/containers"
        caPemstore: "/agent/secrets/ca_cert.crt"
        hostSshVolume: "/agent/.host_ssh"
        scraperConfig: "/agent/etc/scraper.yml"
scraperConfig:
  enable: true
  exporters:
    scrapers:
      node_exporter:
        namespace: "monitoring"
        regex: "node-exporter"
      envoy:
        enabled: true
