global:
  name: "shoreline"
  namespace: "{{ ternary \"shoreline\" .Release.Namespace (eq .Release.Namespace \"default\") }}"
  customer_id: ""
  customer_secret: "secret"
  customer_endpoint: ""
  cloud_provider: "aws" # aws/azure/gcp
  internal: disable
  # certificate: |
  #   -----BEGIN CERTIFICATE-----
  #   -----END CERTIFICATE-----
  # caPemstoreVolumeType: "secret"
agent:
  serviceaccount:
    irsa: false
    aws_role: ""
    runAsNonRoot: false
  # podLabels:
  #   name1: value1
  #   name2: value2
  resource:
    kind: "DaemonSet"
    replicas: 1
    image: "shorelinesoftware/agent"
    tag: "release-x.x.x"
    # imageCredentials:
    #   server: "https://docker.io"
    #   username: "un"
    #   password: "pw"
    # imageCredentialK8sSecret: "pre-existing-k8s-secret"
    hostAction: "enable"
    resources:
      limits:
        cpu: "500m"
        memory: "500Mi"
      requests:
        cpu: "500m"
        memory: "500Mi"
    volumeMounts:
      caPemstoreReadOnly: false
      mountPaths:
        varlog: "/var/log"
        varlibdockercontainers: "/var/lib/docker/containers"
        caPemstore: "/agent/secrets/ca_cert.crt"
        hostSshVolume: "/agent/.host_ssh"
        scraperConfig: "/agent/etc/scraper.yml"
        bareMetalDataVolume: "disable" # /agent/onprem
    hpa: "disable"
    hpaValues:
      minReplicas: 2
      maxReplicas: 6
      metrics:
      - resource:
          name: cpu
          target:
            type: Utilization
            averageUtilization: 80
        type: Resource
      - resource:
          name: memory
          target:
            type: Utilization
            averageUtilization: 80
        type: Resource
      behavior:
        scaleDown:
          stabilizationWindowSeconds: 300
          policies:
          - type: Percent
            value: 100
            periodSeconds: 15
  priorityClassName: ""
scraperConfig:
  enable: true
  exporters:
    scrapers:
      node_exporter:
        namespace: "monitoring"
        regex: "node-exporter"
      envoy:
        enabled: true
